name: medicine_check
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # get image
  image_picker: ^0.8.4+8

  # datetime formatting
  intl: ^0.17.0

  # local notification
  flutter_local_notifications: ^9.1.5
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0

  # permission -> show setting
  permission_handler: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: GmarketSansTTF
      fonts:
        - asset: assets/fonts/gmarket/GmarketSansTTFLight.ttf
          weight: 300
        - asset: assets/fonts/gmarket/GmarketSansTTFMedium.ttf
          weight: 500
        - asset: assets/fonts/gmarket/GmarketSansTTFBold.ttf
          weight: 700
